---
new_page_extension: md
auto_deploy: false
admin_path: "/public/"
webhook_url: 
sections:
- type: directory
  path: contents
  label: Blog Posts
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-article
upload_dir: LRMN
public_path: https://res.cloudinary.com/lrmn/image/upload
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - NEXT_PUBLIC_URL=https://lrmn.is-a.dev
  - NEXT_PUBLIC_EMAIL=lrmn.dev@gmail.com
  preview_output_directory: ".next"
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run build
