name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.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 }}
          publish_dir: ./out
          publish_branch: gh-pages
          force_orphan: true
